### ISSUE TITLE
Meaning of p-value = 0

### ISSUE THREAD

**Issue by ajlee21** [lonelyjoeparker/befi-bats-gui#7]
One of the results I received had a significance value = 0.  Can you tell me more precisely what this value means?  For example the pvalue < what value?

**Comment by lonelyjoeparker** [comment]
The p-value reported is equivalent to the percentile the observed sample (observed values on the posterior set of trees) lies at on the empirical cumulative density function of the expected sample (shuffled values' replicates on PST).

Therefore a p-value of '0' means that all of the expected samples were more extreme (higher) than the observed value. This suggests the observed trait-phylogeny clustering as measured by that metric is highly unlikely to have arisen under the null model (tip states allocated via shuffling using a uniform probability function).

Hope this helps?

**Comment by ajlee21** [comment]
Thank you for your explanation.

The meaning of the p-value is much more clear now.  I was more curious about empirically does p-value = 0 mean p-value <0.001 or some other value?  I'm wondering how extreme this 0 value is?
