### ISSUE TITLE
BaTS Not running

### ISSUE THREAD

**Issue by cibittar** [lonelyjoeparker/befi-bats-gui#8]
[test.trees.txt](https://github.com/lonelyjoeparker/befi-bats-gui/files/374522/test.trees.txt)

Hi,
I am trying to run an analysis on BaTS, as suggested by a reviewer, but it is not working. I am sure it is a simple problem to fix but I don't have the computational skills to figure it out (I’m a biologist). I wrote to Joe, and he suggested to post an issue here.  

Here is the error I am getting:

```
C:\Users\cibittar\BaTS_beta_build2>java -jar BaTS_beta_build2.jar single CxFV4_bats4.trees 100 7
Performing single analysis.
        File: CxFV4_bats4.trees
        Null replicates: 100
        Maximum number of discrete character states: 7
analysing... 10001 trees, with 7 states
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at org.virion.BURPer.node.<init>(node.java:149)
        at org.virion.BURPer.tree.<init>(tree.java:23)
        at org.virion.BURPer.MinimalMassBURPer.singleAnalyse(MinimalMassBURPer.java:55)
        at org.virion.BURPer.GeneralizedSingleBURPer.go(GeneralizedSingleBURPer.java:57)
        at org.virion.burpApp.BaTS_app_beta.main(BaTS_app_beta.java:50)
```

So, here is what I have tried so far…
•	Since I ran my analysis on Beast, I corrected the file as suggested in http://lonelyjoeparker.com/wp/?page_id=274
•	Java version 8
•	Ran the example file – it runs
•	Tried to run about 10 trees – did not work

My OS is Windows 10 (x64) with 8GB RAM.

Sorry if this is a stupid question but I really need help. 
Can anyone help me?

Thanks
Best
Cintia

**Comment by lonelyjoeparker** [comment]
Hi @cibittar - can you please attach the input (10 trees only)?

**Comment by cibittar** [comment]
Hi @lonelyjoeparker,,

Since Github is not allowing to upload the .trees file, I am pasting the input here. I also uploaded a .txt file.

Thanks

#NEXUS

begin states;
1 JapanTokyo
2 JapanTokyo
3 JapanToyama
4 JapanToyama
5 JapanToyama
6 JapanToyama
7 JapanToyama
8 JapanToyama
9 JapanToyama
10 JapanToyama
11 JapanToyama
12 JapanToyama
13 JapanToyama
14 Brazil
15 Mexico
16 USA
17 USA
18 Uganda
19 ChinaLiaoning
20 ChinaLiaoning
21 ChinaLiaoning
22 ChinaLiaoning
23 ChinaLiaoning
24 ChinaLiaoning
25 ChinaLiaoning
26 JapanTokyo
End;
begin trees;
tree STATE_0  = [&R]  (((((6:9.31180785327168,(23:1.5674283601676964,19:1.5674283601676964):7.744379493103985):33.96025120100095,25:43.27205905427263):222.32299145364118,((((8:4.294026998828631,24:4.294026998828631):5.695993480459837,5:9.990020479288468):10.635708118413483,22:20.62572859770195):40.00429063429775,(1:5.74295783326822,18:5.74295783326822):54.88706139873148):204.9650312759141):82.59789140320873,((12:26.70518249229572,7:26.70518249229572):85.20754248248717,16:111.91272497478289):236.28021693633966):1071.0615650935192,(((2:19.15769716810478,15:19.15769716810478):466.16803289590223,(11:267.23629252672737,3:267.23629252672737):218.08943753727965):390.4471133208485,((((26:12.389377605647606,20:12.389377605647606):2.185302507301879,10:14.574680112949485):10.032188270334894,((13:8.081175610425063,(17:1.2695931172361423,21:1.2695931172361423):6.811582493188921):9.551349973903537,9:17.6325255843286):6.974342798955778):105.59908467343836,(14:53.301429595825965,4:53.301429595825965):76.90452346089677):745.5668903281328):543.4816636197862);
tree STATE_1000  = [&R]  ((18:92.0067677917397,15:92.0067677917397):553.3857284686495,(((((22:173.38863801662978,(1:5.5661226358548,2:5.5661226358548):167.82251538077497):69.81518622621371,24:243.2038242428435):14.680138648566583,(((((26:59.33618406397358,17:59.33618406397358):2.9114965274083247,6:62.24768059138191):53.97845372862898,10:116.22613432001089):41.63334663327319,9:157.85948095328408):97.843949109513,((14:94.66093608354328,13:94.66093608354328):119.64183043905908,(19:94.44481573718058,((20:16.280264501625908,21:16.280264501625908):75.89602627723048,25:92.17629077885638):2.2685249583241927):119.85795078542178):41.40066354019473):2.1805328286129964):5.16484302650656,(23:251.74557968873648,((12:17.3069172248752,(7:4.9463873129627105,11:4.9463873129627105):12.36052991191249):182.6701647302887,(4:143.82586957829224,((3:3.3881856181583068,8:3.3881856181583068):11.407880370565882,5:14.79606598872419):129.02980358956805):56.151212376871655):51.76849773357259):11.303226229180154):9.423380934933675,16:272.4721868528503):372.92030940753887);
tree STATE_2000  = [&R]  ((24:109.50245175961267,(23:97.23158558093235,((16:90.29856193983227,(((((6:35.86075889348541,17:35.86075889348541):3.7138440924732805,(12:7.404823729026868,(7:1.147395459127599,11:1.147395459127599):6.257428269899268):32.169779256931825):18.06041349956429,((1:13.305057996932103,26:13.305057996932103):7.235112036184319,2:20.54017003311642):37.09484645240656):28.538484950602424,((10:71.9320302305641,((3:1.3174649004238075,8:1.3174649004238075):7.917544532157777,(5:0.9406913747612845,4:0.9406913747612845):8.2943180578203):62.69702079798251):10.78016357289907,9:82.71219380346317):3.4613076326622405):1.0380872767228766,22:87.21158871284828):3.086973226983986):6.468096017170382,((25:37.69497840905866,((20:16.247451808901744,19:16.247451808901744):2.9576780082227607,21:19.205129817124504):18.48984859193416):48.075620533729165,13:85.77059894278783):10.996059014214822):0.46492762392969667):12.270866178680322):197.8861013636017,((18:92.95810380391714,15:92.95810380391714):32.90371388727283,14:125.86181769118997):181.5267354320244);
tree STATE_3000  = [&R]  (((((((((3:0.5193680809349743,8:0.5193680809349743):12.453392274356588,(10:3.4033677844151415,(4:1.2725948276822707,5:1.2725948276822707):2.130772956732871):9.56939257087642):41.3839783550138,9:54.356738710305365):2.110088591051664,(16:50.07957959626725,22:50.07957959626725):6.387247705089777):0.18101894721404932,(((6:7.375037254429501,(12:6.957119294525591,(7:1.6224271658589784,11:1.6224271658589784):5.334692128666613):0.41791795990391023):12.05241573860025,17:19.42745299302975):10.31947462510512,((1:0.11397704482671556,26:0.11397704482671556):3.0756644630670777,2:3.189641507893793):26.557286110241076):26.90091863043621):1.9383234950158865,13:58.586169743586964):11.693533474364969,(23:52.6689624308386,24:52.6689624308386):17.610740787113336):33.44749823311609,(25:38.50029689984497,((20:10.782522315762945,21:10.782522315762945):0.8900586351381481,19:11.672580950901093):26.827715948943876):65.22690455122306):185.74043664370743,((15:63.622206740727975,14:63.622206740727975):6.064602699426189,18:69.68680944015416):219.7808286546213);
tree STATE_4000  = [&R]  (((((((16:62.694985141417106,22:62.694985141417106):8.61582587133617,(((6:12.252465068901298,(12:7.536598496578682,(7:1.5575743926117551,11:1.5575743926117551):5.9790241039669265):4.715866572322616):18.87589197151147,17:31.12835704041277):8.71553271137434,((1:0.44319051675692445,26:0.44319051675692445):4.911793212813956,2:5.354983729570881):34.48890602221623):31.466921260966167):2.3775321706303174,(((3:1.4652370435909525,8:1.4652370435909525):0.8619467046575735,(4:1.664173540913314,(5:1.0636318419577993,10:1.0636318419577993):0.6005416989555148):0.663010207335212):66.4067048943049,9:68.73388864255342):4.95445454083017):3.132970834232964,13:76.82131401761656):14.834025957321657,(23:66.66954596531028,24:66.66954596531028):24.985794009627938):71.28484860734198,(25:58.97379005805365,((20:13.262685355828802,21:13.262685355828802):1.5048295538087046,19:14.767514909637507):44.20627514841615):103.96639852422655):223.34186354531857,((15:46.70892592835977,14:46.70892592835977):20.790958019638246,18:67.49988394799801):318.7821681796008);
tree STATE_5000  = [&R]  ((((((16:40.35862950307414,22:40.35862950307414):6.0390592838699675,((((6:5.810394061468036,(12:4.130585465889968,(7:1.6481556385694764,11:1.6481556385694764):2.482429827320492):1.6798085955780673):11.742981047241873,17:17.553375108709908):2.8189265835525674,((1:0.02244452633797381,26:0.02244452633797381):2.8847691094672636,2:2.9072136358052374):17.465088056457237):24.708315126689286,(((3:0.671436872625242,8:0.671436872625242):0.345175747722533,((10:0.7676261949857192,5:0.7676261949857192):0.10030125075893925,4:0.8679274457446584):0.1486851746031166):41.343908060681656,9:42.36052068102943):2.720096137922333):1.317071967992348):2.8888321381155464,13:49.286520925059655):8.891164460398649,(23:45.93433946953585,24:45.93433946953585):12.243345915922454):46.070517100133245,(25:46.52934492027227,((20:8.915132000725007,21:8.915132000725007):0.7857687091296306,19:9.700900709854638):36.828444210417636):57.718857565319276):148.45693141066346,((15:26.686849667113567,14:26.686849667113567):12.913605988257057,18:39.600455655370624):213.10467824088437);
tree STATE_6000  = [&R]  ((((((16:55.38114433881049,22:55.38114433881049):10.265555858001811,(((((10:0.6814274821214473,(5:0.31456216267480125,4:0.31456216267480125):0.3668653194466461):0.21410414704176872,3:0.895531629163216):1.0820182251478687,8:1.9775498543110848):59.01745305299023,9:60.99500290730131):3.7905252650570134,(((6:10.933041939765106,(12:8.836964744125078,(7:2.125615718949189,11:2.125615718949189):6.711349025175889):2.096077195640028):13.692572790064988,17:24.625614729830094):6.347423515103909,((1:0.004736454064340014,26:0.004736454064340014):4.12081276872302,2:4.1255492227873605):26.847489022146643):33.81248992742432):0.8611720244539782):4.7273236865000285,13:70.37402388331233):26.93869083263425,(23:79.90287450450353,24:79.90287450450353):17.409840211443054):50.09989717907561,(25:52.63752477863871,((20:12.915145434853407,21:12.915145434853407):1.3110233996338572,19:14.226168834487265):38.41135594415145):94.77508711638347):184.09772705282765,((15:32.25735986404022,14:32.25735986404022):16.959500247758314,18:49.21686011179853):282.2934788360513);
tree STATE_7000  = [&R]  ((((((16:50.09951290115635,22:50.09951290115635):7.446469054601316,((((8:0.7793568964750124,3:0.7793568964750124):0.14305345689884486,(10:0.6013227447882371,(5:0.5238132395451228,4:0.5238132395451228):0.07750950524311429):0.32108760858562013):51.485931343219704,9:52.40834169659356):3.179537716290369,(((6:7.108277391653046,(12:5.237442491589925,(7:0.7630599595394413,11:0.7630599595394413):4.474382532050484):1.8708349000631213):11.125138017646673,17:18.23341540929972):7.8057681536884544,((1:0.3144551628147451,26:0.3144551628147451):2.7863173868989137,2:3.1007725497136587):22.938411013274518):29.548695849895754):1.958102542873739):1.0627611477618188,13:58.60874310351949):19.12236203994661,(23:59.993042409323635,24:59.993042409323635):17.73806273414246):47.0908464533875,(25:45.763915246433214,((20:12.125866211264654,21:12.125866211264654):1.2309727021493106,19:13.356838913413965):32.40707633301925):79.05803635042038):179.68983211105876,((15:27.027539209242295,14:27.027539209242295):14.228060631728578,18:41.25559984097087):263.25618386694146);
tree STATE_8000  = [&R]  ((((((16:30.59540131876133,22:30.59540131876133):3.5298134431985524,((((8:0.34629424618619237,3:0.34629424618619237):0.01546581439354694,((4:0.19659135034260314,5:0.19659135034260314):0.05469079264957674,10:0.2512821429921799):0.11047791758755943):31.937476352689323,9:32.299236413269064):0.9016632585340361,(((6:5.132783177393549,(12:4.372009566096642,(7:0.46288331155059126,11:0.46288331155059126):3.9091262545460506):0.7607736112969068):8.262337864652597,17:13.395121042046146):2.59616269837214,((1:0.18458629726189402,26:0.18458629726189402):2.5503616247396828,2:2.734947922001577):13.256335818416709):17.209615931384814):0.9243150901567816):1.09331737248133,13:35.21853213444121):14.464925804000757,(23:39.54671962287448,24:39.54671962287448):10.136738315567491):29.176150199214497,(25:33.24752327933754,((20:6.467683869266577,21:6.467683869266577):0.8208417967915409,19:7.288525666058118):25.958997613279426):45.61208485831892):104.84816950180118,((15:18.460834772654533,14:18.460834772654533):6.203757211836503,18:24.664591984491036):159.0431856549666);
tree STATE_9000  = [&R]  ((((((16:12.76529046168451,22:12.76529046168451):2.315086900760358,((((3:0.13638365114258402,8:0.13638365114258402):0.005575644277057007,(10:0.08505451187285905,(5:0.061434352234697176,4:0.061434352234697176):0.023620159638161872):0.05690478354678198):13.219832657655317,9:13.361791953074958):1.6553882321747064,(((6:1.8969192873597607,(12:1.3087820567501205,(7:0.4467824577780461,11:0.4467824577780461):0.8619995989720743):0.5881372306096402):3.3362339233317417,17:5.233153210691502):2.379914027520946,((1:0.09198951374430177,26:0.09198951374430177):1.1967410808033558,2:1.2887305945476577):6.3243366436647905):7.404112947037216):0.06319717719520312):1.3698224944514905,13:16.450199856896358):5.146046171671916,(23:16.242262209710518,24:16.242262209710518):5.353983818857756):13.503781017744458,(25:12.754719527857894,((20:3.0591213623917954,21:3.0591213623917954):0.16453852261957636,19:3.223659885011372):9.531059642846522):22.345307518454838):45.144585749845305,((15:8.313318082647607,14:8.313318082647607):2.829442844455441,18:11.142760927103048):69.101851869055);
tree STATE_10000  = [&R]  (((((((((6:1.8829130496964266,(12:1.4609203554396506,(7:0.334036556564957,11:0.334036556564957):1.1268837988746936):0.421992694256776):2.481546815560878,17:4.364459865257305):1.501328843428693,((1:0.06725872465038084,26:0.06725872465038084):1.2043541342426347,2:1.2716128588930156):4.5941758497929825):5.182153762042472,(16:9.79909874657847,22:9.79909874657847):1.2488437241500012):0.01875528943051563,(((8:0.09862638439050096,3:0.09862638439050096):0.03934522676511294,(10:0.0936967441496878,(4:0.0795870527507282,5:0.0795870527507282):0.014109691398959609):0.0442748670059261):10.064393340806138,9:10.202364951961751):0.8643328081972346):0.21891103305285498,13:11.285608793211841):3.283159827487749,(23:11.985734080847344,24:11.985734080847344):2.583034539852246):8.995903552356872,(25:10.157972789261066,((20:2.151141298370673,21:2.151141298370673):0.23134764560913368,19:2.3824889439798067):7.77548384528126):13.406699383795395):31.495734371434732,((15:5.572711899916452,14:5.572711899916452):2.0507434738575094,18:7.623455373773962):47.43695117071723);
End;

[test1.txt](https://github.com/lonelyjoeparker/befi-bats-gui/files/375967/test1.txt)

**Comment by lonelyjoeparker** [comment]
Hi @cibittar from inspecting your input it appears you've not formatted it correctly:

- Whitespace line between states block and trees block missing
- Extra spaces present in tree lines (e.g. ```tree STATE_0  =  [&R] (...```, not ```tree STATE_0 = [&R] (...```

If I correct these I can run your input:

```
joe-parkers-mbp:silene_R9_all joeparker$ oldbats single ~/Downloads/test1.txt 10 7

Performing single analysis.
	File: /Users/joeparker/Downloads/test1.txt
	Null replicates: 10
	Maximum number of discrete character states: 7

analysing... 11 trees, with 7 states
analysing observed (using obs state data)
11 10
11 10
11 10
11 10
11 10
11 10
11 10
11 10
11 10
Statistic	observed mean	lower 95% CI	upper 95% CU	null mean	lower 95% CI	upper 95% CI	significance
AI	0.8783789277076721	0.6831263303756714	1.1620514392852783	2.132434844970703	1.7623845338821411	2.730451822280884	0.0	
PS	8.727272987365723	8.0	10.0	13.527273178100586	12.363636016845703	14.909090995788574	0.0	
MC (state 0)	2.7272727489471436	2.0	3.0	1.1636364459991455	1.0	1.9090908765792847	0.10000002384185791	
MC (state 1)	5.7272725105285645	6.0	6.0	2.299999952316284	1.9090908765792847	3.8181817531585693	0.10000002384185791	
MC (state 2)	1.0	1.0	1.0	1.0	1.0	1.0	1.0	
MC (state 3)	1.0	1.0	1.0	1.0	1.0	1.0	1.0	
MC (state 4)	1.0	1.0	1.0	1.0090909004211426	1.0	1.0909091234207153	1.0	
MC (state 5)	1.0	1.0	1.0	1.0	1.0	1.0	1.0	
MC (state 6)	3.8181817531585693	4.0	4.0	1.4090908765792847	1.0	2.090909004211420.10000002384185791	
done

Done.
```

Please report if this works for you - the spaces can be replaced with a substitution like ```s/\ {2,}/\ /g```

**Comment by cibittar** [comment]
Hey @lonelyjoeparker,

It worked! Thanks! 

Best wishes

**Comment by lonelyjoeparker** [comment]
np - closing #8.
